---
 - hosts: all
   vars_files:
    - /vars/config.yml
   vars:
      actions_runner_download: "https://github.com/actions/runner/releases/download/v2.286.0/actions-runner-linux-x64-2.286.0.tar.gz"
      actions_runner_checksum: "sha256:855b84fe96fda84b22bb9efa2088652d785ed856a7af484b5f4c44f650d7eecf"

   tasks:
    - name: Pre-Requisites ######################################################
      block:
        - name: Download the latest runner package
          get_url:
            url: "{{ actions_runner_download }}"
            dest: /tmp/actions-runner.tar.gz
            checksum: "{{ actions_runner_checksum }}"
            mode: 0655

        - name: Create actions-runner folder
          file:
            path: "~/actions-runner"
            state: directory

        - name: Extract runner
          ansible.builtin.unarchive:
            src: /tmp/actions-runner.tar.gz
            dest: "~/actions-runner"
            remote_src: yes

        - name: Get token for repo
          uri:
            url: "https://api.github.com/repos/{{ github_account }}/{{ github_repo }}/actions/runners/registration-token"
            headers:
              Authorization: "token {{ access_token }}"
              Accept: "application/vnd.github.v3+json"
            method: POST
            status_code: 201
            force_basic_auth: yes
          register: registration
          run_once: yes

        - name: Register runner 
          command:
            "./config.sh --url https://github.com/{{ github_account }} --token {{ registration.json.token }} --name {{ ansible_hostname }} --unattended"
          args:
            chdir: "~/actions-runner"

        - name: Install service
          command: "./svc.sh install {{ runner_user }}"
          args:
            chdir: "~/actions-runner"

        - name: START and enable Github Actions Runner service
          systemd:
            name: "{{ runner_service }}"
            state: started
            enabled: yes
